/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/layout/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Login: typeof import('./src/components/user/Login.vue')['default']
    Register: typeof import('./src/components/user/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/layout/SideBar.vue')['default']
    UserInfo: typeof import('./src/components/user/UserInfo.vue')['default']
    UserManager: typeof import('./src/components/user/UserManager.vue')['default']
    ZjButton: typeof import('./src/components/base/ZjButton.vue')['default']
  }
}
